version: '2'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017

  # flask:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 5000:5000