version: '2'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018

  # flask:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 5000:5000
